language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "stockeh"

script:
  - gradle clean
  - gradle build
  - sonar-scanner -Dsonar.verbose=true -Dsonar.projectKey=stockeh_scalable-server-design -Dsonar.host.url=https://sonarcloud.io -X
