language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "stockeh"

git:
  depth: false

script:
  - echo $SONARQUBE_SCANNER_PARAMS
  - gradle build
  - gradle sonarqube

cache:
  directories:
    - '.gradle'

